### ISSUE TITLE
Fix: SplitMatches.cc:80:25: warning: ISO C++ forbids converting a string constant to ‘char*’

### ISSUE THREAD

**Issue by andy5995** [andy5995/htdig#12]
https://github.com/andy5995/htdig/blob/f41d326ad4fd19cb2412d047fc06ba68d171efbb/htsearch/SplitMatches.cc

```
SplitMatches.cc: In constructor ‘SplitMatches::SplitMatches(Configuration&)’:
SplitMatches.cc:80:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     char *config_item = "search_results_order";
```

**Comment by Davidsksilva** [comment]
Hi, you are initializing a pointer with a string constant. What you want to do is an array of char, for the given constant string, a size of 25 will be more than enought:

`char config_item[25] = "seacrh_reuslts_order"`

Sorry for any inconvenience, first timer here.

**Comment by andy5995** [comment]
It's no inconvenience at all. In fact, you helped me realize that when I post tickets like this, I should mention that I'm asking if anyone is interested in doing a a PR to fix it. Thank you!

@Davidsksilva , are you interested in doing a PR to fix that?

I wonder if `25` should be defined somewhere (#define), so we can use it for other similar variables and keep track of it more easily. Do you have an opinion on that?

TBH, I'm not familiar with the code yet. This was an abandoned project that I became interested in.

Feel free to join the [https://join.slack.com/t/htdig/shared_invite/enQtMjY3NDU1MjMwODk3LTdmM2I2OWI5NWI4MzU4Y2JmMjk2MzAxNDYzM2IzZjJmMGE2MDZmMWMxNDY3MjAwOGFjMmE1YjM2MmM4MzVkNzk](chat room).

**Comment by Ritikkumar1998** [comment]
I am interested in this matter but I am a first timer and don't know anything about PR.
Can anyone guide me. ?

**Comment by andy5995** [comment]
Yes, I've documented instructions at https://github.com/andy5995/htdig/blob/master/CONTRIBUTING.md :)

**Comment by andy5995** [comment]
@Ritikkumar1998 Someone patched this already but please join the chat room and keep in touch if you're still interested in contributing. I'll be filing more tickets soon.

Also, any warnings you see when building you can fix even if no issue for it has been created yet. But only do one PR for each warning message, unless there are multiple warnings coming from 1 file.
