### ISSUE TITLE
implement lighthttpd for testing

### ISSUE THREAD

**Issue by andy5995** [andy5995/htdig#21]
I was looking at http://www.lighttpd.net/ for a light-weight web server. Apache is great of course, but for testing htdig, I think something more minimal would be adequate.

If someone sets this up and documents the process, we can use it for testing.

Once someone sets up lighthttpd , htdig should be able crawl http://localhost and run cgi programs such as htsearch.

We could supply a few html pages so when htdig crawls http://localhost, it will find something. :)

I created a project for this: https://github.com/andy5995/htdig/projects/1

**Comment by andy5995** [comment]
>If someone sets this up and documents the process, we can use it for testing.

There really shouldn't be much to document. How to set up the server should already be documented on the lighthttpd web site.

So the user would have to install it, and make sure the server root points to "samplesite" (see #22). The pages within "samplesite" will be included with the htdig source distribution.

CGI programs would need to be enabled under the lighthttpd server. With the apache server, that can be done using an .htaccess file that looks something like this:
```
Options -ExecCGI
AddHandler cgi-script .pl .sh .cgi 
```
There may be a similar way to do it with lighthttpd

The last option that should be configured for lighthttpd is to only allow connections from localhost. If someone is only using it to test htdig, there's no reason it needs to be listening for connections from the outside world.

@AlexChristoforides Would you be interested in setting this up on your computer, and documenting how to enable the three options? If you can't complete it, don't worry, we'll work through the rest together.

**Comment by AlexChristoforides** [comment]
@andy5995 Yeah! I'll look at it tomorrow!

**Comment by andy5995** [comment]
I was able to work on it a bit today. We can compare notes. :)

I had to install a couple extra libraries.

I decided not to install as root, so I ran
`./configure --prefix=$HOME` ; although I'd suggest `./configure --prefix=$HOME/usr` when the docs are finalized.

I got to the point where I can run the server and execute htsearch through the web form.

My current lighthttpd.conf
```
server.document-root = "/home/andy/src/htdig/samplesite/"

server.modules = (
"mod_cgi",
"mod_accesslog" )

server.port = 3002

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png"
)

static-file.exclude-extensions = ( ".fcgi", ".php", ".rb", "~", ".inc" )
index-file.names = ( "index.html" )

cgi.assign = ( ".sh" => "" )

server.breakagelog = "/home/andy/var/log/lighthttpd/breakage.log"
```

I'm using a bash script as a wrapper to `htsearch. The `${1}` will likely need to be changed, but I'm not sure what's best yet. It works though.

```
#!/bin/bash

echo Content-Type: text/plain
./htsearch ${1}
```

which means I had to modify the extension in the form:

```
  <form action="http://localhost:3002/cgi-bin/htsearch.sh" target=body>
        <b>Quick Search:</b><br>
        <font size="-1">
          <input type=text name=words size=15>
        </font>
      </form>
```

**Comment by andy5995** [comment]
This was completed by c39cd1268c6867dd9c6bd42ec738272fb0fe528c but may need some tweaking
