### ISSUE TITLE
Create a few basic web pages for testing

### ISSUE THREAD

**Issue by andy5995** [andy5995/htdig#22]
This is to help complete #21 and for [project 1](https://github.com/andy5995/htdig/projects/1)

We'll need some sample html web pages for testing. They can be downloaded from any web site, but some of the links they contain will have to be altered so when http://localhost is crawled, the pages can find each other.

It may be easier just to create 3 or 4 web pages with a few lines of arbitrary text that link to each other.

**Comment by AlexChristoforides** [comment]
Would you like the pages to have any styling or are these just used for testing of the application?

**Comment by andy5995** [comment]
>Would you like the pages to have any styling or are these just used for testing the application?

Just for testing, no styling is needed.

I think using `wget` will be the easiest solution. See this web page for more info.

https://superuser.com/questions/1224001/wget-rewriting-directory-links

Have you ever used `wget` before and is this something you'd like to try?

If so, you might have to tweak the options shown in the example above.

As for the web site to mirror... 

I'm pretty sure we'll stay legal if we use http://www.read.gov/aesop/ 

The files would be included with our distribution, but we are non-commercial and not-for-profit.

The mirrored files can go into the htdig source directory under a directory called "samplesite".

After the mirror, this form can be added to the index page

```
     <form action="http://localhost/cgi-bin/htsearch" target=body>
        <b>Quick Search:</b><br>
        <font size="-1">
          <input type=text name=words size=15>
        </font>
      </form>
```

So here is what I have in mind.. when a user has lighthttpd (#11) running, that server root will be where the files we have mirrored our located. The cgi-bin directory in the server root will contain htsearch.

So `htidig` can crawl http://localhost for testing, and `htsearch` can be used on the index.html page 

This way, anyone making significant changes to the source for htdig or htsearch can test their changes in real-time. 

So far, the patches you've submitted don't require testing like that, but you get the idea.

**Comment by andy5995** [comment]
This was completed by c39cd1268c6867dd9c6bd42ec738272fb0fe528c but may need some tweaking
