### ISSUE TITLE
fix warnings in htsearch/Display.cc

### ISSUE THREAD

**Issue by andy5995** [andy5995/htdig#46]
Anyone want to fix some of these warnings?

![screenshot_2017-11-21_17-53-10](https://user-images.githubusercontent.com/16764864/33102970-fd47f546-cee4-11e7-9c55-42b724f301dc.png)

**Comment by tauheed25** [comment]
fixing the style warnings

**Comment by andy5995** [comment]
I see you already submitted a PR for this, but @Debu44 is already working on this issue. (mentioned in the chat room). There is a note in the contributing guidelines about ways to prevent working on issues that other people are already working on.

https://github.com/andy5995/htdig/blob/master/CONTRIBUTING.md

Thank you for the offer though. :)

**Comment by tauheed25** [comment]
I see, my bad I didn't read the contributing section... assumed that no comments meant no-one took ownership!
No problem.. glad to help, had some time to use.

**Comment by andy5995** [comment]
>assumed that no comments meant no-one took ownership!

Normally that would be the case, but I asked about it in the chat room and someone replied later, so the ticket hadn't been updated  yet.

You're welcome to join the chat room and perhaps take another issue if you're interested. I create new ones very frequently.

As for the work you've already done, we may still be able to use it depending on how Debu's patch proceeds; so if you don't mind, hold onto it for a few days. :)

**Comment by tauheed25** [comment]
> You're welcome to join the chat room and perhaps take another issue if you're interested. I create new ones very frequently.
Joined!
> As for the work you've already done, we may still be able to use it depending on how Debu's patch proceeds; so if you don't mind, hold onto it for a few days. :)
Sure, I just pushed a fix, which seems to be passing travis
