### ISSUE TITLE
qtest.cc:72:18: warning: variable ‘override_config’ set but not used

### ISSUE THREAD

**Issue by andy5995** [andy5995/htdig#6]
Anyone interested in doing a PR to fix this?

```
qtest.cc:72:18: warning: variable ‘override_config’ set but not used [-Wunused-but-set-variable]
     int          override_config=0;
```

Feel free to join the [chat room](https://join.slack.com/t/htdig/shared_invite/enQtMjY3NDU1MjMwODk3LTdmM2I2OWI5NWI4MzU4Y2JmMjk2MzAxNDYzM2IzZjJmMGE2MDZmMWMxNDY3MjAwOGFjMmE1YjM2MmM4MzVkNzk).

**Comment by AlexChristoforides** [comment]
I’d love to!

**Comment by andy5995** [comment]
Thanks, @AlexChristoforides , let me know if you've got any questions along the way.

**Comment by AlexChristoforides** [comment]
Which branch should I create the pull request from? Sorry, I'm new...

**Comment by andy5995** [comment]
Oh, no need to apologize. I was new too, once. :)

Can you join the chat room so this ticket doesn't fill up with instructions?

The general instructions are here: https://github.com/andy5995/htdig/blob/master/CONTRIBUTING.md

But let me know if you get stuck somewhere!
